spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:15432/database
    username: user
    password: pass
  flyway:
    schemas: test
    locations: classpath:db/migration,db/dev
  test:
    database:
      replace: none # 実DBを使う設定にする(インメモリDBと入れ替えない)