spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:15432/database?currentSchema=test
    username: user
    password: pass
  flyway:
    schemas: test
    locations: classpath:db/migration,db/dev
  sql.init.mode: always
mybatis:
  configuration:
    map-underscore-to-camel-case: true

