name: Launchable Set Up

env:
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}

runs:
  using: "composite"
#  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
    with:
      fetch-depth: 0 # Launchableのために、フルクローンする必要がある
  - name: Set up JDK 17
    uses: actions/setup-java@v3
    with:
      distribution: 'temurin'
      java-version: 17
  - name: Launchable Python Set Up
    uses: actions/setup-python@v4 # Launchableに必要
    with:
      python-version: "3.10"
  - name: Install launchable command
    run: |
      pip install launchable
