global:
  scrape_interval: "15s"
  evaluation_interval: "15m"
scrape_configs:
  - job_name: "kirimaru"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]