name: Java Set Up
inputs:
  runner-os:
    description: '動作環境'
    required: true
    default: 'Linux'
  gradle-hash:
    description: 'Gradleファイルのハッシュ'
    required: true
    default: 'gradle'

runs:
  using: "composite"
#  runs-on: ubuntu-latest
#  TODO: runner.os　hashFiles等々をパラメータでもらうようにする
  steps:
  - uses: actions/checkout@v3
  - name: Cache gradle modules
    uses: actions/cache@v3
    env:
      cache-name: cache-gradle-modules
    with:
      path: |
        ~/.gradle/caches
        ~/.gradle/wrapper
#        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#      key: linux-gradle-gradle
      key: ${{ inputs.runner-os }}-gradle-${{ gradle-hash }}
      restore-keys: |
#        linux-gradle-
#          ${{ runner.os }}-gradle-
          ${{ inputs.runner-os }}-gradle-
  - name: Set up JDK 17
    uses: actions/setup-java@v3
    with:
      distribution: 'temurin'
      java-version: 17
