info:
  app:
    name: local
    version: 0.0.1
app:
  config:
    appName: "HogeHoge"
spring:
  application:
    name: "kirimaru"
management:
  endpoints:
    web:
      exposure:
        include: "prometheus" # prometheusを有効にする
  metrics:
    tags:
      application: ${spring.application.name}