version: '3.8'
services:
  app:
    image: kirimaru/test-application:latest
    container_name: app
    environment:
      SPRING_PROFILES_ACTIVE: dummy
    restart: always
    depends_on:
      - "database"
    ports:
      - 80:80
    networks: [kirimaru-network]
#    links:　# 今はlinksを使わないほうが良いらしい。
#      - "db:database"
  database:
#  dummy.hostname:
    image: postgres:latest
#    ports:
#      - "15432:5432"
#    container_name: test-container
    container_name: postgres
#    hostname: test-host
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: database
#    hostname: postgres
    hostname: dummy.hostname
    restart: always
    networks: [kirimaru-network]
networks:
  kirimaru-network:
    driver: bridge
#    external:
#      name: kirimaru
#  backend:
#    driver: kirimaru-network
