version: "3.4"
services:
  web:
    image: unleashorg/unleash-server
    ports:
      - "4242:4242"
    environment:
      DATABASE_HOST: "postgres"
      DATABASE_NAME: "unleash"
      DATABASE_USERNAME: "unleash_user"
      DATABASE_PASSWORD: "some_password"
#      DATABASE_URL: "postgres://postgres:unleash@db/postgres"
      DATABASE_SSL: "false"
    depends_on:
      - db
#    command: npm run start
    networks: [unleash]
#    healthcheck:
#      test: ["CMD", "nc",  "-z", "db", "5432"]
#      interval: 1s
#      timeout: 1m
#      retries: 5
#      start_period: 15s
  db:
    expose:
      - "5432"
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "some_password"
      POSTGRES_USER: "unleash_user"
      POSTGRES_DB: "unleash"
#      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks: [unleash]
#    healthcheck:
#      test: ["CMD", "pg_isready", "--username=postgres", "--host=127.0.0.1", "--port=5432"]
#      interval: 2s
#      timeout: 1m
#      retries: 5
#      start_period: 10s
networks:
  unleash:
    driver: bridge

# ログイン
# ID: admin
# PASS: unleash4all
