version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - "15432:5432"
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: database
    hostname: postgres
    restart: always
    networks: &dev_net
      - develop
  redis:
    image: redis:latest
    networks: *dev_net
networks:
  develop: