name: Launchable

on: [push]
#   workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

env:
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # フルクローンする必要がある
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Install launchable command
        run: |
          pip install launchable
      - name: verify
        run: launchable verify
      - name: record build
        run: launchable record build --name ${GITHUB_RUN_ID}
      - name: Run tests
        run: gradle test
      - name: launchable record tests
        run: launchable record tests gradle target/surefire-reports/TEST-example.*.xml
        if: always()
