name: Linter CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
        #     Dockerで使用するならこれでOK
        #     - name: Docker lint
        #       run: |
        #         docker run --rm -i ghcr.io/hadolint/hadolint < Dockerfile
